### ISSUE TITLE
Disabling WebRTC per default does not work as expected

### ISSUE THREAD

**Issue by RalfJung** [ether/ep_webrtc#2]
Steps to reproduce:
Add to the JSON file (to the root of the JSON object, to be precise)

```
    "ep_webrtc" : { "enabled" : false },
```

Expected behaviour:
Per default, the "Enable Audio/Video chat" checkbox should not be checked when I browse to a (new, ore previously not video-enabled) pad.

Actual behaviour:
No difference to without this setting: Every visitor of every pad is asked for webcam access, and the checkbox is always enabled.

Rationale:
I'd like to extend my Etherpad installation with WebRTC, but not all pads will need that. So per default, everything should behave as before, and then there should be some button/checkbox/whatever to enable video, and only then the webcam access question should pop up. I thought this would be possible with the aforementioned JSON setting. If that's not the case, I'd appreciate if you could clarify what the setting does, and consider this as a feature request :)
It'd be even better if that default could be overwritten with the URL somehow, so that access a pad as server/v/padname/webrtc or server/v/padname?webrtc or so, would still automatically enable WebRTC.
I could of course run two instances of etherpad, but then it'd be hard to "upgrade" a pad to A/V after the fact.

Further information:
Etherpad 1.4.0
WebRTC plugin 0.0.1

**Comment by rasos** [comment]
Where can a user launch an AV chat, when it is disabled by default?
Do I need to write and embed my own submit button with 
"ep_webrtc" : { "listenClass": "#chatLabel" }
Shouldn't there be any default button in the left row, to switch on AV? 

I am using webRTC plugin 0.0.6 with
"ep_webrtc" : { "enabled" : false }

**Comment by orblivion** [comment]
I'm just looking through issues to fix now. It looks like @JohnMcLear already fixed this one, or at least it looks fixed to me. As I try it out, `"ep_webrtc" : { "enabled" : ... },` works as @RalfJung was hoping in the issue description (as I understood it).

@RalfJung - Am a reading right that you were (6 years ago now) trying to figure out how to upgrade the plugin to see the fix? Or did you upgrade it and find it still broken?

@rasos - If you click the settings menu (gears icon) you'll see "Enable Audio/Video chat". Checking it will turn on the video, unchecking it will turn it off. Now that the issue was fixed, the `"enabled"` setting _should_ determine its check state on page load. You sure you're running a recent version? (granted, four years ago)

I think that this is all that remains in this issue.

**Comment by RalfJung** [comment]
I do not entirely remember what I did 6 years ago. ;) But I interpret my past self along the lines that I was unable to get the plugin version in my local installation to increase. Either this means displaying the version number is broken, or else the plugin did not update.

**Comment by rasos** [comment]
Still the same behavior:  with `"ep_webrtc" : { "enabled" : false },` any pad is still asking every user to allow camera and microphone being activated. This is a disruptive user experience for all who did not expect video conferencing being included in the pad. 

Setting audio or video to `soft` does not make a difference either and setting both to `hard` shows an error message, that one or both should be enabled (which makes sense).

**Comment by JohnMcLear** [comment]
This plugin needs some real attention, a lot of stuff got broken recently :(

**Comment by rhansen** [comment]
Much has changed recently. This should now be fixed; if not, please open a new bug report.
